//! Rust access to Luau's `IrBuilder` inside a lowering hook.
//!
//! `IrCmd`, `IrCondition`, `IrBlockKind` and `HostMetamethod` are generated by `build.rs` from
//! the headers of the exact Luau build, so a Luau bump that renumbers the IR cannot silently
//! desynchronise this layer. Operands are [`IrOp`] values, opaque 32-bit handles.

use std::ffi::c_int;

use super::ffi;

include!(concat!(env!("OUT_DIR"), "/ir_enums.rs"));

/// Bytecode type tags a `*_type` hook may answer with (`LuauBytecodeType`).
pub mod bytecode_type {
    pub const NIL: u8 = 0;
    pub const BOOLEAN: u8 = 1;
    pub const NUMBER: u8 = 2;
    pub const STRING: u8 = 3;
    pub const TABLE: u8 = 4;
    pub const FUNCTION: u8 = 5;
    pub const THREAD: u8 = 6;
    pub const USERDATA: u8 = 7;
    pub const VECTOR: u8 = 8;
    pub const BUFFER: u8 = 9;
    pub const INTEGER: u8 = 10;
    pub const ANY: u8 = 15;
    /// Userdata type index `i` (into the compilation's `userdata_types`) is `TAGGED_USERDATA_BASE + i`.
    pub const TAGGED_USERDATA_BASE: u8 = 64;
    pub const TAGGED_USERDATA_END: u8 = 64 + 32;
    pub const OPTIONAL_BIT: u8 = 1 << 7;
}

/// An IR operand: a register, constant, block, instruction result, or VM exit.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct IrOp(pub(crate) u32);

impl IrOp {
    pub const NONE: IrOp = IrOp(0);
}

/// Luau's IR builder for the function being compiled, valid for one hook invocation.
pub struct IrBuilder<'a> {
    raw: *mut ffi::db_ir_builder,
    _life: std::marker::PhantomData<&'a mut ()>,
}

impl IrBuilder<'_> {
    pub(crate) unsafe fn from_raw(raw: *mut ffi::db_ir_builder) -> Self {
        IrBuilder { raw, _life: std::marker::PhantomData }
    }

    /// Appends `cmd` with up to eight operands to the current block.
    pub fn inst(&mut self, cmd: IrCmd, ops: &[IrOp]) -> IrOp {
        assert!(ops.len() <= 8, "IrBuilder::inst takes at most eight operands");
        // SAFETY: the builder is live for the hook; ops are plain values.
        IrOp(unsafe { ffi::db_ir_inst(self.raw, cmd as u8, ops.as_ptr().cast::<u32>(), ops.len()) })
    }

    pub fn undef(&mut self) -> IrOp {
        IrOp(unsafe { ffi::db_ir_undef(self.raw) })
    }
    pub fn const_int(&mut self, value: c_int) -> IrOp {
        IrOp(unsafe { ffi::db_ir_const_int(self.raw, value) })
    }
    pub fn const_int64(&mut self, value: i64) -> IrOp {
        IrOp(unsafe { ffi::db_ir_const_int64(self.raw, value) })
    }
    pub fn const_uint(&mut self, value: u32) -> IrOp {
        IrOp(unsafe { ffi::db_ir_const_uint(self.raw, value) })
    }
    pub fn const_import(&mut self, value: u32) -> IrOp {
        IrOp(unsafe { ffi::db_ir_const_import(self.raw, value) })
    }
    pub fn const_double(&mut self, value: f64) -> IrOp {
        IrOp(unsafe { ffi::db_ir_const_double(self.raw, value) })
    }
    /// A Lua type tag constant (`LUA_TNUMBER` and friends).
    pub fn const_tag(&mut self, tag: u8) -> IrOp {
        IrOp(unsafe { ffi::db_ir_const_tag(self.raw, tag) })
    }
    pub fn cond(&mut self, condition: IrCondition) -> IrOp {
        IrOp(unsafe { ffi::db_ir_cond(self.raw, condition as u8) })
    }
    /// A new block of `kind`; the request may be downgraded inside outlined sequences.
    pub fn block(&mut self, kind: IrBlockKind) -> IrOp {
        IrOp(unsafe { ffi::db_ir_block(self.raw, kind as u8) })
    }
    pub fn block_at_inst(&mut self, index: u32) -> IrOp {
        IrOp(unsafe { ffi::db_ir_block_at_inst(self.raw, index) })
    }
    pub fn fallback_block(&mut self, pcpos: u32) -> IrOp {
        IrOp(unsafe { ffi::db_ir_fallback_block(self.raw, pcpos) })
    }
    pub fn begin_block(&mut self, block: IrOp) {
        unsafe { ffi::db_ir_begin_block(self.raw, block.0) }
    }
    /// Loads the tag at `location` and branches to `fallback` unless it is `tag`.
    pub fn load_and_check_tag(&mut self, location: IrOp, tag: u8, fallback: IrOp) {
        unsafe { ffi::db_ir_load_and_check_tag(self.raw, location.0, tag, fallback.0) }
    }
    /// VM register `index`; Luau register operands are eight bits.
    pub fn vm_reg(&mut self, index: c_int) -> IrOp {
        let index = u8::try_from(index).expect("Luau VM register indexes are 0..=255");
        IrOp(unsafe { ffi::db_ir_vm_reg(self.raw, index) })
    }
    pub fn vm_const(&mut self, index: u32) -> IrOp {
        IrOp(unsafe { ffi::db_ir_vm_const(self.raw, index) })
    }
    pub fn vm_upvalue(&mut self, index: u8) -> IrOp {
        IrOp(unsafe { ffi::db_ir_vm_upvalue(self.raw, index) })
    }
    /// The VM exit guards take when a check fails at bytecode position `pcpos`.
    pub fn vm_exit(&mut self, pcpos: c_int) -> IrOp {
        IrOp(unsafe { ffi::db_ir_vm_exit(self.raw, pcpos as u32) })
    }
    pub fn in_terminated_block(&self) -> bool {
        unsafe { ffi::db_ir_in_terminated_block(self.raw) != 0 }
    }
    /// The generic path of the namecall at `pcpos` and the call after it, as Luau translates
    /// them when no hook lowers the pair: a userdata namecall hook emits this on its slow path,
    /// since returning true skips both instructions.
    pub fn namecall_call(&mut self, pcpos: c_int) {
        unsafe { ffi::db_ir_namecall_call(self.raw, pcpos as u32) }
    }
}
