//! Luau type definitions (`.d.luau`) rendered from the resolved plan, so the definition file
//! reflects the final composition (owner plus every augmentation) rather than hand-kept blobs.

use super::install::ModuleMembers;
use super::plan::RuntimePlan;
use super::{MemberKind, ModuleMemberKind, ResolvedUserdata};
use crate::source::CompileConstant;

/// A Luau identifier for a stable key: non-identifier characters become `_`.
pub(crate) fn class_name(key: &str) -> String {
    let mut name: String = key.chars().map(|c| if c.is_ascii_alphanumeric() || c == '_' { c } else { '_' }).collect();
    if name.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        name.insert(0, '_');
    }
    name
}

fn render_userdata(out: &mut String, userdata: &ResolvedUserdata) {
    use std::fmt::Write;
    let _ = writeln!(
        out,
        "-- {} (owned by {}; {})",
        userdata.key,
        userdata.owner,
        match userdata.tag {
            Some(tag) => format!("tag {tag}"),
            None => "untagged".to_owned(),
        }
    );
    if let Some(doc) = &userdata.doc {
        for line in doc.lines() {
            let _ = writeln!(out, "-- {line}");
        }
    }
    let _ = writeln!(out, "declare extern type {} with", class_name(&userdata.key));
    let mut seen_pairs = std::collections::HashSet::new();
    for member in &userdata.members {
        if let Some(doc) = &member.doc {
            for line in doc.lines() {
                let _ = writeln!(out, "    -- {line}");
            }
        }
        match member.kind {
            MemberKind::Method => {
                let signature = member.signature.clone().unwrap_or_else(|| "(self, ...any): any".to_owned());
                let _ = writeln!(out, "    function {}{}", member.name, signature);
            }
            MemberKind::Getter | MemberKind::Setter | MemberKind::Field => {
                if !seen_pairs.insert(member.name.clone()) {
                    continue;
                }
                let ty = member
                    .signature
                    .clone()
                    .or_else(|| {
                        userdata
                            .members
                            .iter()
                            .find(|m| m.name == member.name && m.signature.is_some())
                            .and_then(|m| m.signature.clone())
                    })
                    .unwrap_or_else(|| "any".to_owned());
                let _ = writeln!(out, "    {}: {ty}", member.name);
            }
        }
    }
    let _ = writeln!(out, "end\n");
}

fn constant_type(constant: &CompileConstant) -> &'static str {
    match constant {
        CompileConstant::Nil => "nil",
        CompileConstant::Boolean(_) => "boolean",
        CompileConstant::Number(_) => "number",
        CompileConstant::Integer(_) => "integer",
        CompileConstant::Vector(..) => "vector",
        CompileConstant::String(_) => "string",
    }
}

/// Renders the definitions for `plan`: every userdata type and every module with its declared
/// members. The plan knows the whole shape before a VM exists, so nothing here waits for an
/// installed runtime; `members` (a runtime's installed record) is accepted for callers that
/// have one and ignored.
pub(crate) fn render_with(plan: &RuntimePlan, members: Option<&ModuleMembers>) -> String {
    use std::fmt::Write;
    let _ = members;
    let mut out = String::new();
    let _ = writeln!(out, "-- Generated by l3i from the runtime plan; do not edit.");
    let _ = writeln!(out, "-- Extensions: {}\n", plan.installation_order().join(", "));
    for userdata in &plan.userdata {
        render_userdata(&mut out, userdata);
    }
    for module in &plan.modules {
        let type_name = format!("Module_{}", class_name(&module.path));
        let _ = writeln!(out, "-- module {} (provided by {})", module.path, module.provider);
        if let Some(doc) = &module.doc {
            for line in doc.lines() {
                let _ = writeln!(out, "-- {line}");
            }
        }
        let _ = writeln!(out, "export type {type_name} = {{");
        for member in &module.members {
            if let Some(doc) = &member.doc {
                for line in doc.lines() {
                    let _ = writeln!(out, "    -- {line}");
                }
            }
            let ty = match (&member.signature, &member.kind) {
                (Some(signature), _) => signature.clone(),
                (None, ModuleMemberKind::Function) => "(...any) -> ...any".to_owned(),
                (None, ModuleMemberKind::Constant(constant)) => constant_type(constant).to_owned(),
                (None, ModuleMemberKind::Installed) => "any".to_owned(),
            };
            let _ = writeln!(out, "    {}: {ty},", member.name);
        }
        let _ = writeln!(out, "}}");
        if let Some(global) = &module.global {
            let _ = writeln!(out, "declare {global}: {type_name}");
        }
        out.push('\n');
    }
    out
}

pub(crate) fn render(plan: &RuntimePlan) -> String {
    render_with(plan, None)
}
